- .vscode/tasks.json
- autoreduce_frontend/autoreduce_webapp/backends.py
- autoreduce_frontend/autoreduce_webapp/icat_cache.py
- autoreduce_frontend/autoreduce_webapp/icat_communication.py
- autoreduce_frontend/autoreduce_webapp/uows_client.py
- autoreduce_frontend/autoreduce_webapp/view_utils.py
- autoreduce_frontend/instrument/views/runs.py
- autoreduce_frontend/instrument/views/variables.py
- autoreduce_frontend/plotting/plot_handler.py
- autoreduce_frontend/reduction_viewer/view_utils.py
- autoreduce_frontend/reduction_viewer/views.py
- autoreduce_frontend/selenium_tests/tests/test_rerun_jobs_range_integration.py
Replace getLogger('app') with filename to get in line with [AR-1445](https://autoreduce.atlassian.net/browse/AR-1445)
Fixes #xyz
> Replace getLogger('app') with `__package__`

- autoreduce_frontend/selenium_tests/utils.py
Try counting number of completed runs. Rather than accessing the internal state in a way it's not meant to be accessed.
A SELECT should be OK on the SQLite3 DB, I think only parallel attempts to write cause it to lock
Fixes #xyz
> Second attempt at fixing the unreliable test

- autoreduce_frontend/autoreduce_webapp/settings.py
- autoreduce_frontend/selenium_tests/configuration.py
- autoreduce_frontend/selenium_tests/tests/base_tests.py
- setup.py
> Change settings imports and use newer utils

- requirements.txt
- setup.py
> Updates version and requirements packages

- autoreduce_frontend/autoreduce_webapp/fixtures/two_runs_failed.json
- autoreduce_frontend/reduction_viewer/views.py
- autoreduce_frontend/selenium_tests/pages/failed_jobs_page.py
- autoreduce_frontend/selenium_tests/tests/pages/test_failed_jobs.py
- autoreduce_frontend/static/css/base.css
- autoreduce_frontend/static/javascript/runs_failed.js
- autoreduce_frontend/templates/fail_queue.html
* Tests pass
* Code review
* Create lots of failed runs and test that the pagination works
Fixes [AR-1373](https://autoreduce.atlassian.net/browse/AR-1373)
Fixes [AR-1374](https://autoreduce.atlassian.net/browse/AR-1374)
> Fix failed runs table

- autoreduce_frontend/reduction_viewer/view_utils.py
Docstring and formatting changes. Only syntax change is the removal of a redundant else block (functionally is still the same).
> Docstring and formatting changes

- autoreduce_frontend/autoreduce_webapp/templatetags/common_helpers.py
- autoreduce_frontend/autoreduce_webapp/templatetags/natural_time_difference.py
- autoreduce_frontend/autoreduce_webapp/templatetags/test/test_natural_time_difference.py
- autoreduce_frontend/autoreduce_webapp/uows_client.py
- autoreduce_frontend/autoreduce_webapp/urls.py
- autoreduce_frontend/autoreduce_webapp/view_utils.py
- autoreduce_frontend/autoreduce_webapp/views.py
- autoreduce_frontend/autoreduce_webapp/wsgi.py
Refactor repetitive code and fix docstrings. Add coverage for `natural_time_difference.py`.
> Refactor code and fix docstrings

- .pre-commit-config.yaml
- autoreduce_frontend/reduction_viewer/view_utils.py
- autoreduce_frontend/reduction_viewer/views.py
- autoreduce_frontend/selenium_tests/pages/run_summary_page.py
- autoreduce_frontend/selenium_tests/tests/pages/test_run_summary.py
- autoreduce_frontend/templates/run_summary.html
Added a toggle button next to the "Data" location to switch between Unix and Windows path formats.
Added selenium test for Data path in summary and toggle button.
Navigate to a run summary, press the toggle button next to "Data: ".
Should reload same run but change path format for Data.
> 1348 datapath toggle ar 1348

- autoreduce_frontend/selenium_tests/tests/integration/test_run_summary_integration.py
Add test that checks datetime respects BST. Fix docstrings and formatting.
Related to AR-753
> Add test that checks datetime repsects BST

- autoreduce_frontend/autoreduce_webapp/urls.py
- autoreduce_frontend/generate_token/forms.py
- autoreduce_frontend/generate_token/views.py
- autoreduce_frontend/reduction_viewer/filters.py
- autoreduce_frontend/reduction_viewer/views/common.py
- autoreduce_frontend/reduction_viewer/views/configure_new_batch_run.py
- autoreduce_frontend/reduction_viewer/views/run_summary.py
- autoreduce_frontend/reduction_viewer/views/variables.py
- autoreduce_frontend/selenium_tests/pages/run_summary_page.py
- autoreduce_frontend/selenium_tests/pages/variables_summary_page.py
- autoreduce_frontend/selenium_tests/tests/base_tests.py
- autoreduce_frontend/selenium_tests/tests/integration/test_configure_new_runs_integration.py
- autoreduce_frontend/selenium_tests/tests/pages/test_configure_new_batch_runs.py
- autoreduce_frontend/selenium_tests/tests/pages/test_configure_new_runs.py
- autoreduce_frontend/selenium_tests/tests/pages/test_run_summary_plots.py
- autoreduce_frontend/selenium_tests/tests/pages/test_see_instrument_variables.py
> Fix pylint issues

- .github/workflows/run-tests.yml
- autoreduce_frontend/reduction_viewer/views/run_summary.py
- autoreduce_frontend/templates/run_summary.html
- container/webapp.D
- setup.py
> Properly display all data locations for batch runs

- autoreduce_frontend/generate_token/urls.py
- autoreduce_frontend/selenium_tests/pages/configure_new_batch_run_page.py
> Add a check for user login when accessing tokens/ app

- ansible/roles/run/webapp/start/meta/main.yml
- ansible/roles/run/webapp/start/tasks/main.yml
- autoreduce_frontend/reduction_viewer/urls.py
- container/webapp.D
- setup.py
> Redirect to login on submit batch run

- .github/workflows/run-tests.yml
- autoreduce_frontend/selenium_tests/pages/accessibility_statement_page.py
- autoreduce_frontend/selenium_tests/pages/component_mixins/footer_mixin.py
- autoreduce_frontend/selenium_tests/pages/component_mixins/navbar_mixin.py
- autoreduce_frontend/selenium_tests/pages/component_mixins/rerun_form_mixin.py
- autoreduce_frontend/selenium_tests/pages/component_mixins/tour_mixin.py
- autoreduce_frontend/selenium_tests/pages/configure_new_batch_run_page.py
- autoreduce_frontend/selenium_tests/pages/configure_new_runs_page.py
- autoreduce_frontend/selenium_tests/pages/error_page.py
- autoreduce_frontend/selenium_tests/pages/experiment_summary_page.py
- autoreduce_frontend/selenium_tests/pages/failed_jobs_page.py
- autoreduce_frontend/selenium_tests/pages/generate_token/delete_page.py
- autoreduce_frontend/selenium_tests/pages/generate_token/generate_page.py
- autoreduce_frontend/selenium_tests/pages/generate_token/list_page.py
- autoreduce_frontend/selenium_tests/pages/help_page.py
- autoreduce_frontend/selenium_tests/pages/job_queue_page.py
- autoreduce_frontend/selenium_tests/pages/overview_page.py
- autoreduce_frontend/selenium_tests/pages/rerun_jobs_page.py
- autoreduce_frontend/selenium_tests/pages/run_summary_page.py
- autoreduce_frontend/selenium_tests/pages/runs_list_page.py
- autoreduce_frontend/selenium_tests/pages/search_page.py
- autoreduce_frontend/selenium_tests/pages/variables_summary_page.py
- autoreduce_frontend/selenium_tests/tests/integration/test_configure_new_runs_integration.py
- autoreduce_frontend/selenium_tests/tests/integration/test_rerun_jobs_range_integration.py
- autoreduce_frontend/selenium_tests/tests/pages/test_run_summary.py
- autoreduce_frontend/selenium_tests/tests/pages/test_see_instrument_variables.py
- requirements.txt
Upgrade to Selenium 4
Remove use of container from dependeancy-check, as local python is no longer tied to reduction python
Fix deprecation warnings
> 1562 selenium 4 ar 1562

- .github/workflows/run-tests.yml
- requirements.txt
- setup.py
Update Django to 4.0.1
Update other requirements
Update Python to 3.8
> Update django 4.0

- autoreduce_frontend/autoreduce_webapp/settings.py
- autoreduce_frontend/autoreduce_webapp/urls.py
- requirements.txt
Bump Django toolbar from 3.2.2 to 3.2.4
> Bump django toolbar

- autoreduce_frontend/templates/run_confirmation.html
- autoreduce_frontend/templates/run_summary.html
Add rel="noopener noreferrer" to links to fix security issue raised by CodeQL
> fix security issues with opening links

- autoreduce_frontend/selenium_tests/tests/base_tests.py
- autoreduce_frontend/selenium_tests/tests/integration/test_batch_run_summary_integration.py
- autoreduce_frontend/selenium_tests/tests/integration/test_run_summary_integration.py
- autoreduce_frontend/selenium_tests/utils.py
- container/webapp.D
- setup.py
> Initial kafka

- .github/workflows/run-tests.yml
- Makefile
> Update selenium in tests

- autoreduce_frontend/autoreduce_webapp/settings.py
- setup.py
> Use env for allowed hosts

- setup.py
> Increment qp version

- autoreduce_frontend/selenium_tests/tests/base_tests.py
> Fix reference to old github URL

- README.md
- pyproject.toml
> Fix missing README and reference

- .github/workflows/run-tests.yml
We no longer need to publish to PyPi, so we will stop.
Code review
Fixes #155
Release notes updates are not necessary.
> Remove pypi publishing
